### ISSUE TITLE
Missing Bugtab

### ISSUE THREAD

**Issue by theblackturtle** [janmasarik/bugshop#1]
Hi bro, I see you mention about `Bugtab` in your book and in README section but I can't find it in this repos. Can you share it? Thanks.

**Comment by theblackturtle** [comment]
I found it.

**Comment by 1hack0** [comment]
Hi @theblackturtle 

Could you tell me where the Bugtab is? I could not find it.

Thanks!

**Comment by theblackturtle** [comment]
You can download here: https://is.muni.cz/th/de05t/

**Comment by 1hack0** [comment]
Hi @theblackturtle 
Thanks a lot! I got it. I am lost in config of the bugshop. I am newbie for k8s argo gitlab. :(
